name: DMD Reader Continuous Integration Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'pip'
        cache-dependency-path: 'requirements_dev.txt'
    - name: Install dependencies
      run: pip install -r requirements_dev.txt
    - name: Running example code
      run: python example.py
    - name: Analyzing the code with pylint
      run: python -m pylint .
